[build]
  command = "npm install && npm run netlify-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
